name: test

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

  workflow_call:

jobs:
  tscheck:
    name: lint and tscheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: tscc
        run: npm run tscc
      - name: tsccd
        run: npm run tsccd
